name: Lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name: Run Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install client dependencies
        run: npm ci
        working-directory: client

      - name: Install server dependencies
        run: npm ci
        working-directory: server

      - name: Run linting
        run: npm run lint